services:
  - type: web
    name: smt-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn smt_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smt_backend.settings.prod
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: smt-backend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REFRESH_COOKIE_SECURE
        value: "True"
      - key: REFRESH_COOKIE_SAMESITE
        value: None
