# Generated by Django 5.0.4 on 2026-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_remove_customer_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='fruits_expe_date_4d3598_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='fruits_expe_categor_169359_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='fruits_purc_created_047b74_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='fruits_sale_created_1629f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_type', 'created_at'], name='fruits_sale_payment_928168_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreturn',
            index=models.Index(fields=['created_at'], name='fruits_stoc_created_9702c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreturn',
            index=models.Index(fields=['return_type', 'created_at'], name='fruits_stoc_return__e6068b_idx'),
        ),
    ]
