# Generated by Django 5.0.4 on 2026-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_expense_fruits_expe_date_4d3598_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
