# Generated by Django 6.0.3 on 2026-04-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0006_customerpayment_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('customer', 'Customer Return (Stock In)'), ('supplier', 'Supplier Return/Wastage (Stock Out)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.product')),
            ],
        ),
    ]
