# Generated by Django 6.0.3 on 2026-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0007_stockreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreturn',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='return_type',
            field=models.CharField(choices=[('customer', 'Customer Return (Stock In)'), ('supplier', 'Supplier Return (Stock Out)'), ('wastage', 'Wastage/Spoiled (Stock Out - Loss)')], max_length=20),
        ),
    ]
