# Generated by Django 6.0.3 on 2026-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0008_stockreturn_loss_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity / Utilities'), ('transport', 'Transportation'), ('salary', 'Staff Salary'), ('packaging', 'Packaging Materials'), ('other', 'Other Miscellaneous')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
