# Generated by Django 6.0.3 on 2026-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0010_alter_customer_options_alter_customerpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreturn',
            name='return_type',
            field=models.CharField(choices=[('customer', 'Customer Return (Restock)'), ('wastage', 'Wastage/Spoiled (Stock Out - Loss)'), ('supplier', 'Supplier Return (Stock Out - No Loss)')], db_index=True, max_length=20),
        ),
    ]
