# Generated by Django 6.0.3 on 2026-04-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0011_alter_stockreturn_return_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreturn',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text="Required if return_type is 'supplier'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruits.supplier'),
        ),
    ]
